version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - checkout
      - save_cache:
          key: pix-{{ checksum ".circle-sha" }}
          paths:
            - ~/pix

  install_client_dependencies:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - pix-
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
            - client-dependencies-
      - run: npm install
      - save_cache:
          key: client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
          paths:
            - ~/pix/live/node_modules
            - ~/pix/live/bower_components
            - ~/.npm
            - ~/.cache/bower

  build_client:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - pix-
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
            - client-dependencies-
      - run: ./node_modules/.bin/ember build

      - save_cache:
          key: client_app-{{ checksum ".circle-sha" }}
          paths:
            - dist

  deploy_client:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - pix-
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
            - client-dependencies-
            - client_app-{{ checksum ".circle-sha" }}
            - client_app-
      - run: npm run deploy:integration

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install_client_dependencies:
          requires:
            - checkout_code
      - build_client:
          requires:
            - install_client_dependencies
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              ignore:
                - master
                - dev
