version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
          paths:
            - ~/pix

  bundle_dependencies:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-npm-cache-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-dependencies-npm-root-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-npm-root-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-dependencies-npm-live-{{ .Branch }}-{{ checksum "live/package.json" }}
            - v1-dependencies-npm-live-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-dependencies-bower-live-{{ .Branch }}-{{ checksum "live/bower.json" }}
            - v1-dependencies-bower-live-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-dependencies-npm-api-{{ .Branch }}-{{ checksum "api/package.json" }}
            - v1-dependencies-npm-api-{{ .Branch }}
      - run: npm install
      - save_cache:
          key: v1-npm-cache-{{ .Branch }}
          paths:
            - ~/.npm
      - save_cache:
          key: v1-dependencies-npm-root-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/pix/node_modules
      - save_cache:
          key: v1-dependencies-npm-root-{{ .Branch }}
          paths:
            - ~/pix/node_modules
      - save_cache:
          key: v1-dependencies-npm-live-{{ .Branch }}-{{ checksum "live/package.json" }}
          paths:
            - ~/pix/api/node_modules
      - save_cache:
          key: v1-dependencies-npm-live-{{ .Branch }}
          paths:
            - ~/pix/api/node_modules
      - save_cache:
          key: v1-dependencies-bower-live-{{ .Branch }}-{{ checksum "live/bower.json" }}
          paths:
            - ~/pix/api/bower_components
      - save_cache:
          key: v1-dependencies-bower-live-{{ .Branch }}
          paths:
            - ~/pix/api/bower_components
      - save_cache:
          key: v1-dependencies-npm-api-{{ .Branch }}-{{ checksum "api/package.json" }}
          paths:
            - ~/pix/live/node_modules
      - save_cache:
          key: v1-dependencies-npm-api-{{ .Branch }}
          paths:
            - ~/pix/live/node_modules
      - save_cache:
          key: v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
          paths:
            - ~/pix/node_modules
            - ~/pix/api/node_modules
            - ~/pix/live/node_modules
            - ~/pix/live/bower_components

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Lint files
          command: npm run lint

  build_pix_live:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}

      - run: ./node_modules/.bin/ember build

      - save_cache:
          key: v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}
          paths:
            - dist

  npm_test_api:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: npm run test:api

  npm_test_live_1:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=4 --partition=1

  npm_test_live_2:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=4 --partition=2

  npm_test_live_3:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=4 --partition=3

  npm_test_live_4:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-build-live-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=4 --partition=4


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - build_pix_live:
          requires:
            - bundle_dependencies
      - lint:
          requires:
            - bundle_dependencies
      - npm_test_api:
          requires:
            - bundle_dependencies
      - npm_test_live_1:
          requires:
            - build_pix_live
      - npm_test_live_2:
          requires:
            - build_pix_live
      - npm_test_live_3:
          requires:
            - build_pix_live
      - npm_test_live_4:
          requires:
            - build_pix_live
