version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - checkout
      - run:
          name: save SHA to a file (root)
          command: echo $CIRCLE_SHA1 > .circle-sha
      - run:
          name: save SHA to a file (api)
          command: echo $CIRCLE_SHA1 > api/.circle-sha
      - run:
          name: save SHA to a file (live)
          command: echo $CIRCLE_SHA1 > live/.circle-sha
      - save_cache:
          key: repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/pix

  bundle_dependencies_root:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "package.json" }}-v1
      - run: npm install --ignore-scripts
      - save_cache:
          key: npm-cache-{{ .Branch }}
          paths:
            - ~/.npm
      - save_cache:
          key: dependencies-root-{{ checksum "package.json" }}-v1
          paths:
            - ~/pix/node_modules
            - ~/.npm

  bundle_dependencies_api:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/api
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-api-{{ checksum "package.json" }}-v1
      - run: npm install
      - save_cache:
          key: dependencies-api-{{ checksum "package.json" }}-v1
          paths:
            - ~/pix/api/node_modules
            - ~/pix/.npm

  bundle_dependencies_live:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1
      - run: npm install
      - save_cache:
          key: dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1
          paths:
            - ~/pix/live/node_modules
            - ~/pix/live/bower_components
            - ~/.npm
            - ~/.cache/bower

  lint_api:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/api
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-api-{{ checksum "package.json" }}-v1
      - run:
          name: Lint files
          command: npm run lint

  lint_live:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1
      - run:
          name: Lint files
          command: npm run lint

  build_pix_live:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1

      - run: ./node_modules/.bin/ember build

      - save_cache:
          key: build-live-{{ checksum ".circle-sha" }}
          paths:
            - dist

  npm_test_api:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/api
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-api-{{ checksum "package.json" }}-v1
      - run:
          name: Run Tests
          command: npm run test

  npm_test_live_1:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1
      - restore_cache:
          keys:
            - build-live-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=2 --partition=1

  npm_test_live_2:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-root-{{ checksum "../package.json" }}-v1
      - restore_cache:
          keys:
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v1
      - restore_cache:
          keys:
            - build-live-{{ checksum ".circle-sha" }}
      - run:
          name: Run Tests
          command: ./node_modules/.bin/ember exam --path dist --split=2 --partition=2


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies_root:
          requires:
            - checkout_code
      - bundle_dependencies_api:
          requires:
            - checkout_code
      - bundle_dependencies_live:
          requires:
            - checkout_code
      - lint_api:
          requires:
            - bundle_dependencies_root
            - bundle_dependencies_api
      - lint_live:
          requires:
            - bundle_dependencies_root
            - bundle_dependencies_live
      - build_pix_live:
          requires:
            - bundle_dependencies_root
            - bundle_dependencies_live
      - npm_test_api:
          requires:
            - bundle_dependencies_root
            - bundle_dependencies_api
      - npm_test_live_1:
          requires:
            - build_pix_live
      - npm_test_live_2:
          requires:
            - build_pix_live
