version: 2.0

jobs:

  checkout_code:
    docker:
      - image: circleci/node:8
      - image: circleci/node:8-browsers
    working_directory: ~/pix
    steps:
      - checkout
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: pix-{{ checksum ".circle-sha" }}-v7
          paths:
            - ~/pix

  install_client_dependencies:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}-v7
      - restore_cache:
          keys:
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v7
      - run: npm install
      - save_cache:
          key: client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v7
          paths:
            - ~/pix/live/node_modules
            - ~/pix/live/bower_components
            - ~/.npm
            - ~/.cache/bower

  build_client:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}-v7
      - restore_cache:
          keys:
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v7
      - run: ./node_modules/.bin/ember build

      - save_cache:
          key: client_app-{{ checksum ".circle-sha" }}-v7
          paths:
            - dist

  deploy_client:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}-v7
      - restore_cache:
          keys:
            - client-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
      - restore_cache:
          keys:
            - client_app-{{ checksum ".circle-sha" }}-v7
      # cf. https://circleci.com/docs/2.0/gh-bb-integration/#adding-readwrite-deployment-keys-to-github-or-bitbucket
      - add-ssh-keys:
          fingerprints:
            - "c3:0d:1b:26:62:f1:89:98:d8:8c:f2:6c:b1:25:7b:6b"
      - run: npm run deploy:integration

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout_code
      - install_client_dependencies:
          requires:
            - checkout_code
      - build_client:
          requires:
            - install_client_dependencies
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              ignore:
                - master
                - dev
                - gh-pages
