version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix
    steps:
      - checkout
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: pix-{{ checksum ".circle-sha" }}
          paths:
            - ~/pix

  bundle_dependencies_root:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - dependencies-root-{{ checksum "package.json" }}-v2
      - run: npm install --ignore-scripts
      - save_cache:
          key: dependencies-root-{{ checksum "package.json" }}-v2
          paths:
            - ~/pix/node_modules
            - ~/.npm

  bundle_dependencies_live:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - dependencies-root-{{ checksum "../package.json" }}-v2
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v2
      - run: npm install
      - save_cache:
          key: dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v2
          paths:
            - ~/pix/live/node_modules
            - ~/pix/live/bower_components
            - ~/.npm
            - ~/.cache/bower

  build_pix_live:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/pix/live
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - dependencies-root-{{ checksum "../package.json" }}-v2
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v2

      - run: ./node_modules/.bin/ember build

      - save_cache:
          key: build-live-{{ checksum ".circle-sha" }}
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/pix/live
    steps:
      - restore_cache:
          keys:
            - pix-{{ checksum ".circle-sha" }}
            - dependencies-root-{{ checksum "../package.json" }}-v2
            - dependencies-live-{{ checksum "package.json" }}-{{ checksum "bower.json" }}-v2
            - build-live-{{ checksum ".circle-sha" }}
      - run: npm run deploy:integration

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies_root:
          requires:
            - checkout_code
      - bundle_dependencies_live:
          requires:
            - checkout_code
      - build_pix_live:
          requires:
            - bundle_dependencies_root
            - bundle_dependencies_live
      - deploy:
          requires:
            - build_pix_live
          filters:
            branches:
              ignore:
                - master
                - dev
